# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 21:56
from __future__ import unicode_literals

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170929_1146'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
