# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170929_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name_initial',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
