# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 01:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170929_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Name or title must begin with a capital letter.', regex='^[A-Z][a-z]*$')]),
        ),
    ]
