# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teaching',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('course', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together=set([('course', 'user')]),
        ),
    ]
